#Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.12.0'

#Importing dataset

In [3]:
dataset = pd.read_csv('/content/drive/MyDrive/ANN/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
ann = tf.keras.models.Sequential()

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [16]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.5527 - accuracy: 0.7862
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4811 - accuracy: 0.7954
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4432 - accuracy: 0.7975
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4185 - accuracy: 0.8108
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4023 - accuracy: 0.8217
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3908 - accuracy: 0.8286
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3830 - accuracy: 0.8320
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3777 - accuracy: 0.8334
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3734 - accuracy: 0.8386
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3698 - accura

In [18]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1507   88]
 [ 190  215]]


0.861

In [23]:
ann.save("trained_model.h5")  # Save as HDF5 file

In [24]:
loaded_model = tf.keras.models.load_model("trained_model.h5")


In [25]:
predictions = loaded_model.predict(X_test)


63/63 [==============================] - 0s 2ms/step


In [26]:
from google.colab import files

files.download('trained_model.h5')


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>